services:
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        calls:
            - [setMailer, ["@mailer"]]
            - [setTemplating, ["@templating"]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }